### ISSUE TITLE
Doesn't seem to support size-adjusted images

### ISSUE THREAD

**Issue by B0BIC** [rxliuli/mami#2]
Using mami so far for joplin -> docsify and it's going great, but it doesn't seem to support images where the image's size has been adjusted:

![image](https://github.com/rxliuli/mami/assets/3453126/0f60a834-f582-40e2-bb9e-3e716870a4c9)

![image](https://github.com/rxliuli/mami/assets/3453126/5010c478-0767-401d-ad26-ca6214206753)

I notice now that these images are contained in an html tag which has a class modifier(? don't know the terminology) called "jop-noMdConv." 

Is this more a problem with docsify? Or could you add an option in the converter to change the resized images to non-resized images? Sorry, I'm kind of a novice with all this stuff, but I'd appreciate some help if possible!

Thanks again for making such a cool app!

Edit: I checked again, and the file exists in resources:

![image](https://github.com/rxliuli/mami/assets/3453126/68609e8a-8b1c-4d30-a0c0-8a5dbbda3105)

So I'm not sure if it's an issue with mami or docsify?

EDIT2: seems to be working when I manually change the <img> tag to the following (adding "resources" at the beginning and ".jpg" at the end):

`<img src="resources/a87e73075f1e405fba416e0450157b71.jpg" alt="IMG_9101.JPG" width="623" height="415" class="jop-noMdConv">`

**Comment by rxliuli** [comment]
Please update @mami/* related modules, the following html tags are now supported

img/audio/video
